cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"
tap "daipeihust/tap"

brew "nnn"
brew "fzf"
brew "lsd"
brew "bat"
brew "git"
brew "tig"
brew "hub"
brew "tree"
brew "tmux"
brew "node"
brew "java"
brew "deno"
brew "make"
brew "pure"
brew "ctags"
brew "neovim"
brew "ripgrep"
brew "im-select"
brew "clang-format"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# cask "drawio"
cask "vivaldi"
# cask "mactex-no-gui"
cask "alacritty"
cask "1password"
cask "tailscale"
cask "google-drive"
# cask "input-source-pro"
cask "karabiner-elements"
cask "font-jetbrains-mono-nerd-font"
