cask_args appdir: "/Applications"

tap "homebrew/cask-fonts"
tap "koekeishiya/formulae"

brew "nnn"
brew "fzf"
brew "lsd"
brew "bat"
brew "font-jetbrains-mono-nerd-font"
brew "tree"
brew "tmux"
brew "neovim"
brew "clang-format"
brew "defaultbrowser"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

cask "vivaldi"
cask "alacritty"
cask "1password"
cask "google-drive"
